phi0836.phi002
PerseusDL/canonical-latinLit pull request #405
Opened 2021-03-30 18:58 UTC by AlisonBabeu

Updated the cts.xml
Took first pass at updating and standardizing the headers.
Thanks for any and all feedback @lcerrato

2021-03-31 19:00 UTC, lcerrato requested changes

2021-03-31 19:00 UTC, lcerrato commented on data/phi0836/phi002/phi0836.phi002.perseus-lat4.xml
> +							<date>1971</date>
You can type a date, so `<date type="reprint">`

2021-03-31 19:21 UTC, capitains-hook commented
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5355)*

2021-04-01 21:16 UTC, AlisonBabeu commented
Hii @lcerrato I will make this change plus I also need to add URLs into the headers.

2021-04-02 21:45 UTC, capitains-hook commented
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-latinLit/5357)*

2021-04-06 20:01 UTC, lcerrato approved these changes

2021-04-06 20:49 UTC, merged