(phi0959)_phi0959.phi001.perseus-eng2/lat2
PerseusDL/canonical-latinLit pull request #460
Opened 2022-01-11 19:36 UTC by AlisonBabeu

My first efforts at updating Perseus headers for Ovid, and I have already hit several questions for you @lcerrato 

1) Ovid is the name for the textggroup, but I have left the Latin name`<author xml:lang="lat">P. Ovidius Naso</author>`for the author name in these first two files as you recommended using M. Tullius Cicero for Cicero in the headers and bibliographic descriptions for his workis.

2) In phi0959.phi001.perseus-eng2 I found `<respStmt>
							<name>Anne Mahoney</name>
							<resp>edited for Perseus</resp>
						</respStmt>`
within the `<monogr>`section. I'm pretty sure this is incorrect, because shouldn't this section just have bibliographic information regarding the original publication. There is actually no editor for this 1855 publication, or none named. Shouldn't this editor statement regarding Anne be added up to the `respStmt` in the `</titleStmt>`.

3) I'm not sure what to do about the `<ti:description>` for phi0959.phi001.perseus-eng2.  There was originally a full list of the translators with dates and all (there are 10!)  with translator repeated and I've tightened this up. It is still a lot of data for this field and I was wondering if I should just change it to Dryden, John, translators, et. al. or something like that and wanted your thoughts on that. (All of the data on the translators is in the catalog record)

Other than that I just updated the header and cts information to current standards and added in reference links.  Thanks for any and all suggestions.

2022-01-12 16:38 UTC, lcerrato requested changes

2022-01-12 16:38 UTC, lcerrato commented on data/phi0959/phi001/__cts__.xml
> +      <ti:label xml:lang="eng">Amores.</ti:label>
No period after Amores

2022-01-12 16:38 UTC, lcerrato commented on data/phi0959/phi001/__cts__.xml
> +            Beauty, the Court of Love, the History of Love, and Amours. Dryden, John; Creech, Thomas; Hopkins, Charles;
@AlisonBabeu I would use "Dryden, John, et al., translator."  here. I have shortened this elsewhere.

2022-01-12 16:40 UTC, lcerrato commented
@AlisonBabeu Yes, Anne should be moved up to the `<respStmt>` list in this case.

2022-01-12 18:55 UTC, AlisonBabeu commented
Ok. Thanks for the answers.  I'm sure I will have more questions as I proceed with Ovia.

2022-01-13 17:55 UTC, lcerrato approved these changes

2022-01-13 17:55 UTC, lcerrato commented on data/phi0959/phi001/phi0959.phi001.perseus-eng2.xml
> +					<name>Anne Mahoney</name>
@AlisonBabeu 
This is fine here since we know the work done, but this is generally alphabetical.

2022-01-13 21:33 UTC, merged